version: "3.3"

services:
  por_portal_frontend:
    image: por_portal_frontend
    container_name: por_portal_frontend
    restart: always
    build:
        context: .
    ports:
      - "9834:3000"
    env_file:
    - ".env"
    command: sh -c "cd /app && serve -s build"
    networks:
      - frontend_default

networks:
  frontend_default:
    external: true