version: '2'

services:
  web:
    image: por_portal_backend
    container_name: por_portal_backend
    build: 
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9501:3002"
    volumes:
      - .:/code/uploads
