version: '3.3'

services:
  por_portal_backend:
    image: por_portal_backend
    container_name: por_portal_backend
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9501:3002"
    volumes:
      - ./uploads:/code/uploads
    env_file:
      - ".env"
    networks:
      - backend_sports-board-strapi



networks:
  backend_sports-board-strapi:
    external: true
