const recipients = [
  { email: "techsec@iitg.ac.in", por: "Technical Board" },
  { email: "iitgai@iitg.ac.in", por: "AI Club" },
  { email: "saeindia_iitg@iitg.ac.in", por: "Automobile club" },
  { email: "electronicsclub@iitg.ac.in", por: "Electronics club" },
  { email: "edc@iitg.ac.in", por: "E-Cell" },
  { email: "aeroclub@iitg.ac.in", por: "Aeromodeling Club" },
  { email: "cac@iitg.ac.in", por: "Consulting & Analytics Club" },
  { email: "codingclub@iitg.ac.in", por: "Coding Club" },
  { email: "finneco@iitg.ac.in", por: "Finance & Economics Club" },
  { email: "roboclub@iitg.ac.in", por: "Robotics Club" },
  { email: "prakriti@iitg.ac.in", por: "Prakriti Cllub" },
  { email: "quizclub@iitg.ac.in", por: "Quiz club" },
  { email: "sports@iitg.ac.in", por: "Sports Board" },
  { email: "athleticsec@iitg.ac.in", por: "Athletics Club" },
  { email: "aquaticsec@iitg.ac.in", por: "Aquatics Club" },
  { email: "basketballsec@iitg.ac.in", por: "Basketball" },
  { email: "badmintonsec@iitg.ac.in", por: "Badminton" },
  { email: "cricketsec@iitg.ac.in", por: "Cricket Club" },
  { email: "footballsec@iitg.ac.in", por: "Football Club" },
  { email: "hockeysec@iitg.ac.in", por: "Hockey Club" },
  { email: "tennissec@iitg.ac.in", por: "Lawn Tennis Club" },
  { email: "squashsec@iitg.ac.in", por: "Squash Club" },
  { email: "tabletennissec@iitg.ac.in", por: "Table Tennis Club" },
  { email: "weightliftingsec@iitg.ac.in", por: "Weightlifting Club" },
  { email: "volleyballsec@iitg.ac.in", por: "Volleyball Club" },
  { email: "cultsec@iitg.ac.in", por: "Cultural Board" },
  { email: "cadence@iitg.ac.in", por: "Dance Club" },
  { email: "anr@iitg.ac.in", por: "Anchoring Club" },
  { email: "finesse@iitg.ac.in", por: "Fine Arts club" },
  { email: "montage@iitg.ac.in", por: "Photography club" },
  { email: "lumiere@iitg.ac.in", por: "Movie club" },
  { email: "octaves@iitg.ac.in", por: "Music Club" },
  { email: "xpressions@iitg.ac.in", por: "Drama Club" },
  { email: "litsoc@iitg.ac.in", por: "Literary club" },
  { email: "gensec_welfare@iitg.ac.in", por: "SWB" },
  { email: "saathi@iitg.ac.in", por: "Saathi Counselling Cell" },
  { email: "lambda@iitg.ac.in", por: "Lambda" },
  { email: "socialserviceclub@iitg.ac.in", por: "Social Service Club" },
  { email: "yec@iitg.ac.in", por: "Youth Empowerment Club" },
  { email: "rrc@iitg.ac.in", por: "Red Ribbon Club" },
  { email: "spirit@iitg.ac.in", por: "Spirit" },
  { email: "alcheringa@iitg.ac.in", por: "Alcheringa" },
  { email: "techniche@iitg.ac.in", por: "Techniche" },
  { email: "reflux@iitg.ac.in", por: "Reflux" },
  { email: "udgam@iitg.ac.in", por: "Udgam" },
  { email: "sail@iitg.ac.in", por: "SAIL" },
  { email: "tedxiitg@iitg.ac.in", por: "Tedx" },
  { email: "swc@iitg.ac.in", por: "SWC" },
  { email: "sab@iitg.ac.in", por: "SAB" },
  { email: "research_conclave@iitg.ac.in", por: "Research and Industrial Conclave" },
  { email: "awareness_club@iitg.ac.in", por: "Awareness Club" },
  { email: "tarangini@iitg.ac.in", por: "Tarangini Club" },
  { email: "4ilab@iitg.ac.in", por: "4i Lab" },
  { email: "aic@iitg.ac.in", por: "Academic Initiatives Club" },
  { email: "esgd@iitg.ac.in", por: "GameDev and Esports Club" },
  { email: "wsds@iitg.ac.in", por: "Whitespace" },
  { email: "haboff@iitg.ac.in", por: "HAB" },
  { email: "nss@iitg.ac.in", por: "NSS" },
  { email: "ishanya@iitg.ac.in", por: "Ishanya DoD" },
  { email: "equinox@iitg.ac.in", por: "Astronomy Club" }
];

export default recipients;
